default:
  # build this from "gitlab-runner directory"
  # add >pull_policy "if-not-present"< in gitlab runner config.toml
  # if you have no docker registry
  image: builder-node-java

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"


cache:
  #key: ${CI_COMMIT_REF_SLUG}
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node/node_modules
    - maven.repository
  
stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/node 
    - npm install
    - cd ${CI_PROJECT_DIR}/maven
    - mvn compile

test-code-job1:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/node 
    - npm run test
    - cd ${CI_PROJECT_DIR}/maven
    - mvn verify
