default:
  # build this from "gitlab-runner directory"
  # add >pull_policy "if-not-present"< in gitlab runner config.toml
  # if you have no docker registry
  image: builder-node-go

cache:
  #key: ${CI_COMMIT_REF_SLUG}
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node/node_modules
    - .go/pkg/mod/

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    #key: ${CI_COMMIT_REF_SLUG}
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node/node_modules
      - .go/pkg/mod/
  
stages:
  - build
  - test

build-code-job:
  stage: build
  extends: .go-cache
  script:
    - cd ${CI_PROJECT_DIR}/node 
    - npm install
    - cd ${CI_PROJECT_DIR}/go
    - go mod download
    - go build

test-code-job1:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/node 
    - npm run test

test-code-job2:
  stage: test
  script:
    - echo "If the files are built successfully, test other files with a different command:"
    - echo "rake test2"
