all: builder-buildpack builder-node builder-node-dotnet builder-node-go builder-node-java


.PHONY: builder-buildpack
builder-buildpack:
	cd $@ && make

.PHONY: builder-node
builder-node:
	cd $@ && make

.PHONY: builder-node-dotnet
builder-node-dotnet:
	cd $@ && make

.PHONY: builder-node-go
builder-node-go:
	cd $@ && make

.PHONY: builder-node-java
builder-node-java:
	cd $@ && make

