default:
  # build this from "gitlab-runner directory"
  # add >pull_policy "if-not-present"< in gitlab runner config.toml
  # if you have no docker registry
  image: builder-node-dotnet

variables:
  NUGET_PACKAGES_DIRECTORY: '${CI_PROJECT_DIR}/.nuget'

cache:
  #key: ${CI_COMMIT_REF_SLUG}
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node/node_modules
    - '$NUGET_PACKAGES_DIRECTORY'
  
stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/node 
    - npm install
    - cd ${CI_PROJECT_DIR}/dotnet
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    - dotnet build --no-restore
    - dotnet publish --no-restore

test-code-job1:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/node 
    - npm run test
    - cd ${CI_PROJECT_DIR}/dotnet
    #- dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    #- dotnet test --no-restore
