default:
  image: builder-node

cache:
  #key: ${CI_COMMIT_REF_SLUG}
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules
  
stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - npm install

test-code-job:
  stage: test
  script:
    - npm run test

