default:
  # build this from "gitlab-runner directory"
  # add >pull_policy "if-not-present"< in gitlab runner config.toml
  # if you have no docker registry
  image: builder-buildpack

cache:
  #key: ${CI_COMMIT_REF_SLUG}
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - ccache/
    - native/build/_deps/ # 3rd party stuff cmake downloads
  
stages:
  - build
  - test

before_script:
  # CCache Config
  - mkdir -p ${CI_PROJECT_DIR}/ccache
  - export CCACHE_BASEDIR=${CI_PROJECT_DIR}
  - export CCACHE_DIR=${CI_PROJECT_DIR}/ccache

build-code-job:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/native
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - make

test-code-job1:
  stage: test
  script:
    - echo "test test"
